name: Metrics

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
  
jobs:
  metrics:
    runs-on: ubuntu-latest
      
    steps:
      - name: Contribution Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0

      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: US/Eastern

      - name: Languages Used
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_indepth: yes

      - name: Using classic charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes

      - name: Using chartist charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/stargazers.chartist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist

      - name: Repositories traffic
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/traffic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_traffic: yes

      - name: Pinned repositories
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/repositories.pinned.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_repositories: yes
          plugin_repositories_pinned: 6
          plugin_repositories_forks: yes
