name: Metrics

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
  
jobs:
  metrics:
    runs-on: ubuntu-latest
      
    steps:
      - name: Current year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0

      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
