name: Metrics

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Languages
      uses: lowlighter/metrics@latest
      with:
        filename: languages.svg
        token: ${{ secrets.METRICS_TOKEN }}
        plugin_languages: yes
        plugin_languages_indepth: yes
        commits_authoring: firstname lastname, username, username@users.noreply.github.com
    
    - name: Current year calendar
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.calendar.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_calendar: yes

    - name: Using classic charts
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.stargazers.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_stargazers: yes

    - name: Using chartist charts
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.stargazers.chartist.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_stargazers: yes
        plugin_stargazers_charts_type: chartist  
